name: firebase_manager
description: Firebase manager to manage firebase operations
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  firebase_auth: ^3.7.0
  google_sign_in: ^5.4.1
  http: ^0.13.5
  cloud_firestore: ^3.4.7
  firebase_storage: ^10.3.8
